if-shell 'command -v powerline-config >/dev/null' {
    run-shell 'powerline-config tmux setup'
}
bind a send-prefix

set -g history-limit 50000

set -g mouse on
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -g status-interval 5
setw -g aggressive-resize on


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# 启用自动恢复功能
set -g @continuum-restore 'on'

# (可选) 配置开机自启 (需系统支持 systemd)
set -g @continuum-boot 'on'

set -g @plugin "arcticicestudio/nord-tmux"

run '~/.tmux/plugins/tpm/tpm'

